<?xml version="1.0" encoding="utf-8"?><Database Name="QLCHBANGIAY" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-T8SC55E\SQLEXPRESS;Initial Catalog=QLCHBANGIAY;User ID=sa" SettingsObjectName="GiaoDien.Properties.Settings" SettingsPropertyName="QLCHBANGIAY_MoiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QUANLYND" Member="QUANLYNDs">
    <Type Name="QUANLYND">
      <Column Name="TENDN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MK" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="QUANLYND_QLNDNHOMND" Member="QLNDNHOMNDs" ThisKey="TENDN" OtherKey="TENDN" Type="QLNDNHOMND" />
      <Association Name="NHANVIEN_QUANLYND" Member="NHANVIEN" ThisKey="TENDN" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QLNDNHOMND" Member="QLNDNHOMNDs">
    <Type Name="QLNDNHOMND">
      <Column Name="TENDN" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QUANLYND_QLNDNHOMND" Member="QUANLYND" ThisKey="TENDN" OtherKey="TENDN" Type="QUANLYND" IsForeignKey="true" />
      <Association Name="QLNHOMND_QLNDNHOMND" Member="QLNHOMND" ThisKey="MANHOM" OtherKey="MANHOM" Type="QLNHOMND" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QLNHOMND" Member="QLNHOMNDs">
    <Type Name="QLNHOMND">
      <Column Name="MANHOM" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QLNHOMND_QLNDNHOMND" Member="QLNDNHOMNDs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QLNDNHOMND" />
      <Association Name="QLNHOMND_QLPHANQUYEN" Member="QLPHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QLPHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.QLPHANQUYEN" Member="QLPHANQUYENs">
    <Type Name="QLPHANQUYEN">
      <Column Name="MANHOM" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMANHINH" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="QLNHOMND_QLPHANQUYEN" Member="QLNHOMND" ThisKey="MANHOM" OtherKey="MANHOM" Type="QLNHOMND" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BIENBANSUCO" Member="BIENBANSUCOs">
    <Type Name="BIENBANSUCO">
      <Column Name="MABB" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NGAYLAPBB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="BIENBANSUCO_CTBBSC" Member="CTBBSCs" ThisKey="MABB" OtherKey="MABB" Type="CTBBSC" />
      <Association Name="BIENBANSUCO_CTTKSC" Member="CTTKSCs" ThisKey="MABB" OtherKey="MABB" Type="CTTKSC" />
      <Association Name="NHANVIEN_BIENBANSUCO" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTBBSC" Member="CTBBSCs">
    <Type Name="CTBBSC">
      <Column Name="MABB" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASC" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THU_CHI" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="BIENBANSUCO_CTBBSC" Member="BIENBANSUCO" ThisKey="MABB" OtherKey="MABB" Type="BIENBANSUCO" IsForeignKey="true" />
      <Association Name="DMSUCO_CTBBSC" Member="DMSUCO" ThisKey="MASC" OtherKey="MASC" Type="DMSUCO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SIZEGIAY" Member="SIZEGIAYs">
    <Type Name="SIZEGIAY">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOSIZE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONGTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_SIZEGIAY" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUBAOHANH" Member="PHIEUBAOHANHs">
    <Type Name="PHIEUBAOHANH">
      <Column Name="MABH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="NGAYHETHANDOITRA" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="PHIEUBAOHANH_CHITIETHOADONBAN" Member="CHITIETHOADONBANs" ThisKey="MABH" OtherKey="MABH" Type="CHITIETHOADONBAN" />
      <Association Name="KHACHHANG_PHIEUBAOHANH" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_PHIEUBAOHANH" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUBAOHANH" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANGKH" Member="DONDATHANGKHs">
    <Type Name="DONDATHANGKH">
      <Column Name="MADH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TONGSLSANPHAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DONDATHANGKH_GIAOHANG" Member="GIAOHANGs" ThisKey="MADH" OtherKey="MADH" Type="GIAOHANG" />
      <Association Name="DONDATHANGKH_CHITIETDDHKHACHHANG" Member="CHITIETDDHKHACHHANGs" ThisKey="MADH" OtherKey="MADH" Type="CHITIETDDHKHACHHANG" />
      <Association Name="KHACHHANG_DONDATHANGKH" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIAOHANG" Member="GIAOHANGs">
    <Type Name="GIAOHANG">
      <Column Name="MADH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANVGIAOHANG" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYGIOGIAOHANG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="DONDATHANGKH_GIAOHANG" Member="DONDATHANGKH" ThisKey="MADH" OtherKey="MADH" Type="DONDATHANGKH" IsForeignKey="true" />
      <Association Name="HOADONBAN_GIAOHANG" Member="HOADONBAN" ThisKey="MAHD" OtherKey="MAHD" Type="HOADONBAN" IsForeignKey="true" />
      <Association Name="NHANVIEN_GIAOHANG" Member="NHANVIEN" ThisKey="MANVGIAOHANG" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDDHKHACHHANG" Member="CHITIETDDHKHACHHANGs">
    <Type Name="CHITIETDDHKHACHHANG">
      <Column Name="MADH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONGSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIATIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DONDATHANGKH_CHITIETDDHKHACHHANG" Member="DONDATHANGKH" ThisKey="MADH" OtherKey="MADH" Type="DONDATHANGKH" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETDDHKHACHHANG" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUCSP" Member="DANHMUCSPs">
    <Type Name="DANHMUCSP">
      <Column Name="MADMSP" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDMSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DANHMUCSP_SANPHAM" Member="SANPHAMs" ThisKey="MADMSP" OtherKey="MADMSP" Type="SANPHAM" />
      <Association Name="DANHMUCSP_KHO" Member="KHOs" ThisKey="MADMSP" OtherKey="MADMSP" Type="KHO" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTKHACHHANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIACHIKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_PHIEUBAOHANH" Member="PHIEUBAOHANHs" ThisKey="MAKH" OtherKey="MAKH" Type="PHIEUBAOHANH" />
      <Association Name="KHACHHANG_DONDATHANGKH" Member="DONDATHANGKHs" ThisKey="MAKH" OtherKey="MAKH" Type="DONDATHANGKH" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MADMSP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MAU" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CHATLIEU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOLUONGSIZE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TINHTRANGSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="SANPHAM_SIZEGIAY" Member="SIZEGIAYs" ThisKey="MASP" OtherKey="MASP" Type="SIZEGIAY" />
      <Association Name="SANPHAM_PHIEUBAOHANH" Member="PHIEUBAOHANHs" ThisKey="MASP" OtherKey="MASP" Type="PHIEUBAOHANH" />
      <Association Name="SANPHAM_CHITIETDDHKHACHHANG" Member="CHITIETDDHKHACHHANGs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETDDHKHACHHANG" />
      <Association Name="SANPHAM_KHO" Member="KHOs" ThisKey="MASP" OtherKey="MASP" Type="KHO" />
      <Association Name="SANPHAM_CTTKD" Member="CTTKDs" ThisKey="MASP" OtherKey="MASP" Type="CTTKD" />
      <Association Name="SANPHAM_CHITIETHOADONBAN" Member="CHITIETHOADONBANs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETHOADONBAN" />
      <Association Name="SANPHAM_CT_KHUYENMAI" Member="CT_KHUYENMAIs" ThisKey="MASP" OtherKey="MASP" Type="CT_KHUYENMAI" />
      <Association Name="SANPHAM_LICHSUGIA" Member="LICHSUGIAs" ThisKey="MASP" OtherKey="MASP" Type="LICHSUGIA" />
      <Association Name="SANPHAM_CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETPHIEUNHAP" />
      <Association Name="SANPHAM_CTPHIEUDATHANGNCC" Member="CTPHIEUDATHANGNCCs" ThisKey="MASP" OtherKey="MASP" Type="CTPHIEUDATHANGNCC" />
      <Association Name="DANHMUCSP_SANPHAM" Member="DANHMUCSP" ThisKey="MADMSP" OtherKey="MADMSP" Type="DANHMUCSP" IsForeignKey="true" />
      <Association Name="LOAIGIAY_SANPHAM" Member="LOAIGIAY" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAIGIAY" IsForeignKey="true" />
      <Association Name="NHACC_SANPHAM" Member="NHACC" ThisKey="MANCC" OtherKey="MANCC" Type="NHACC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHO" Member="KHOs">
    <Type Name="KHO">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MADMSP" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="DANHMUCSP_KHO" Member="DANHMUCSP" ThisKey="MADMSP" OtherKey="MADMSP" Type="DANHMUCSP" IsForeignKey="true" />
      <Association Name="SANPHAM_KHO" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="LOAIGIAY_KHO" Member="LOAIGIAY" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAIGIAY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOIDUNG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PHANTRAM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="APDUNG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KHUYENMAI_CHITIETHOADONBAN" Member="CHITIETHOADONBANs" ThisKey="MAKM" OtherKey="MAKM" Type="CHITIETHOADONBAN" />
      <Association Name="KHUYENMAI_CT_KHUYENMAI" Member="CT_KHUYENMAIs" ThisKey="MAKM" OtherKey="MAKM" Type="CT_KHUYENMAI" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONBAN" Member="HOADONBANs">
    <Type Name="HOADONBAN">
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CHIECKHAU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MAKHTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KHVANGLAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HOADONBAN_GIAOHANG" Member="GIAOHANGs" ThisKey="MAHD" OtherKey="MAHD" Type="GIAOHANG" />
      <Association Name="HOADONBAN_CHITIETHOADONBAN" Member="CHITIETHOADONBANs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHOADONBAN" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIGIAY" Member="LOAIGIAYs">
    <Type Name="LOAIGIAY">
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAIGIAY_SANPHAM" Member="SANPHAMs" ThisKey="MALOAI" OtherKey="MALOAI" Type="SANPHAM" />
      <Association Name="LOAIGIAY_KHO" Member="KHOs" ThisKey="MALOAI" OtherKey="MALOAI" Type="KHO" />
      <Association Name="LOAIGIAY_CTTKD" Member="CTTKDs" ThisKey="MALOAI" OtherKey="MALOAI" Type="CTTKD" />
    </Type>
  </Table>
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="MACHUCVU" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LUONG" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CHUCVU_NHANVIEN" Member="NHANVIENs" ThisKey="MACHUCVU" OtherKey="MACHUCVU" Type="NHANVIEN" />
    </Type>
  </Table>
  <Table Name="dbo.THONGKE_DS" Member="THONGKE_Ds">
    <Type Name="THONGKE_D">
      <Column Name="MATKDS" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MADMTK" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAPTK" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGSODS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIENDS" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="THONGKE_D_CTTKD" Member="CTTKDs" ThisKey="MATKDS" OtherKey="MATKDS" Type="CTTKD" />
      <Association Name="DMTK_THONGKE_D" Member="DMTK" ThisKey="MADMTK" OtherKey="MADMTK" Type="DMTK" IsForeignKey="true" />
      <Association Name="NHANVIEN_THONGKE_D" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGKE_SC" Member="THONGKE_SCs">
    <Type Name="THONGKE_SC">
      <Column Name="MATKSC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MADMTK" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAPTK" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGSOSC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTHU_CHI" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="THONGKE_SC_CTTKSC" Member="CTTKSCs" ThisKey="MATKSC" OtherKey="MATKSC" Type="CTTKSC" />
      <Association Name="DMTK_THONGKE_SC" Member="DMTK" ThisKey="MADMTK" OtherKey="MADMTK" Type="DMTK" IsForeignKey="true" />
      <Association Name="NHANVIEN_THONGKE_SC" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGKE_CUOINAM" Member="THONGKE_CUOINAMs">
    <Type Name="THONGKE_CUOINAM">
      <Column Name="MATKCN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MADMTK" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAPTK" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIENDS_CN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DMTK_THONGKE_CUOINAM" Member="DMTK" ThisKey="MADMTK" OtherKey="MADMTK" Type="DMTK" IsForeignKey="true" />
      <Association Name="NHANVIEN_THONGKE_CUOINAM" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTTKSC" Member="CTTKSCs">
    <Type Name="CTTKSC">
      <Column Name="MATKSC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MABB" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THU_CHI" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="BIENBANSUCO_CTTKSC" Member="BIENBANSUCO" ThisKey="MABB" OtherKey="MABB" Type="BIENBANSUCO" IsForeignKey="true" />
      <Association Name="THONGKE_SC_CTTKSC" Member="THONGKE_SC" ThisKey="MATKSC" OtherKey="MATKSC" Type="THONGKE_SC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTTKDS" Member="CTTKDs">
    <Type Name="CTTKD">
      <Column Name="MATKDS" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="LOAIGIAY_CTTKD" Member="LOAIGIAY" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAIGIAY" IsForeignKey="true" />
      <Association Name="SANPHAM_CTTKD" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="THONGKE_D_CTTKD" Member="THONGKE_D" ThisKey="MATKDS" OtherKey="MATKDS" Type="THONGKE_D" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMTK" Member="DMTKs">
    <Type Name="DMTK">
      <Column Name="MADMTK" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LOAITHONGKE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DMTK_THONGKE_D" Member="THONGKE_Ds" ThisKey="MADMTK" OtherKey="MADMTK" Type="THONGKE_D" />
      <Association Name="DMTK_THONGKE_SC" Member="THONGKE_SCs" ThisKey="MADMTK" OtherKey="MADMTK" Type="THONGKE_SC" />
      <Association Name="DMTK_THONGKE_CUOINAM" Member="THONGKE_CUOINAMs" ThisKey="MADMTK" OtherKey="MADMTK" Type="THONGKE_CUOINAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SOCMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIENTHOAINV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MACHUCVU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYVAOLAM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANQL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="THUONGDOANHTHU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LUONGTRU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THUCLANH" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="NHANVIEN_QUANLYND" Member="QUANLYND" ThisKey="MANV" OtherKey="TENDN" Type="QUANLYND" Cardinality="One" />
      <Association Name="NHANVIEN_BIENBANSUCO" Member="BIENBANSUCOs" ThisKey="MANV" OtherKey="MANV" Type="BIENBANSUCO" />
      <Association Name="NHANVIEN_PHIEUBAOHANH" Member="PHIEUBAOHANHs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUBAOHANH" />
      <Association Name="NHANVIEN_GIAOHANG" Member="GIAOHANGs" ThisKey="MANV" OtherKey="MANVGIAOHANG" Type="GIAOHANG" />
      <Association Name="NHANVIEN_THONGKE_D" Member="THONGKE_Ds" ThisKey="MANV" OtherKey="MANV" Type="THONGKE_D" />
      <Association Name="NHANVIEN_THONGKE_SC" Member="THONGKE_SCs" ThisKey="MANV" OtherKey="MANV" Type="THONGKE_SC" />
      <Association Name="NHANVIEN_THONGKE_CUOINAM" Member="THONGKE_CUOINAMs" ThisKey="MANV" OtherKey="MANV" Type="THONGKE_CUOINAM" />
      <Association Name="NHANVIEN_NHANVIEN" Member="NHANVIENs" ThisKey="MANV" OtherKey="MANQL" Type="NHANVIEN" />
      <Association Name="NHANVIEN_PHIEUDATHANGNCC" Member="PHIEUDATHANGNCCs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUDATHANGNCC" />
      <Association Name="NHANVIEN_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MANV" OtherKey="MANV" Type="PHIEUNHAP" />
      <Association Name="CHUCVU_NHANVIEN" Member="CHUCVU" ThisKey="MACHUCVU" OtherKey="MACHUCVU" Type="CHUCVU" IsForeignKey="true" />
      <Association Name="NHANVIEN_NHANVIEN" Member="NHANVIEN1" ThisKey="MANQL" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADONBAN" Member="CHITIETHOADONBANs">
    <Type Name="CHITIETHOADONBAN">
      <Column Name="MACTHDB" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MABH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAKM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONGBAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIABAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOSIZE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUBAOHANH_CHITIETHOADONBAN" Member="PHIEUBAOHANH" ThisKey="MABH" OtherKey="MABH" Type="PHIEUBAOHANH" IsForeignKey="true" />
      <Association Name="HOADONBAN_CHITIETHOADONBAN" Member="HOADONBAN" ThisKey="MAHD" OtherKey="MAHD" Type="HOADONBAN" IsForeignKey="true" />
      <Association Name="KHUYENMAI_CHITIETHOADONBAN" Member="KHUYENMAI" ThisKey="MAKM" OtherKey="MAKM" Type="KHUYENMAI" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETHOADONBAN" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_KHUYENMAI" Member="CT_KHUYENMAIs">
    <Type Name="CT_KHUYENMAI">
      <Column Name="MAKM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NBD" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KHUYENMAI_CT_KHUYENMAI" Member="KHUYENMAI" ThisKey="MAKM" OtherKey="MAKM" Type="KHUYENMAI" IsForeignKey="true" />
      <Association Name="SANPHAM_CT_KHUYENMAI" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICHSUGIA" Member="LICHSUGIAs">
    <Type Name="LICHSUGIA">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYAPDUNG" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MUCGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="SANPHAM_LICHSUGIA" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACC" Member="NHACCs">
    <Type Name="NHACC">
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTNHACC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHINCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHACC_SANPHAM" Member="SANPHAMs" ThisKey="MANCC" OtherKey="MANCC" Type="SANPHAM" />
      <Association Name="NHACC_PHIEUDATHANGNCC" Member="PHIEUDATHANGNCCs" ThisKey="MANCC" OtherKey="MANCC" Type="PHIEUDATHANGNCC" />
      <Association Name="NHACC_PHIEUNHAP" Member="PHIEUNHAPs" ThisKey="MANCC" OtherKey="MANCC" Type="PHIEUNHAP" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUDATHANGNCC" Member="PHIEUDATHANGNCCs">
    <Type Name="PHIEUDATHANGNCC">
      <Column Name="SODONHANG" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIENNHAP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TINHTRANGHANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTIENTRATRUOC" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PHIEUDATHANGNCC_CTPHIEUDATHANGNCC" Member="CTPHIEUDATHANGNCCs" ThisKey="SODONHANG" OtherKey="SODONHANG" Type="CTPHIEUDATHANGNCC" />
      <Association Name="NHACC_PHIEUDATHANGNCC" Member="NHACC" ThisKey="MANCC" OtherKey="MANCC" Type="NHACC" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUDATHANGNCC" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAP" Member="PHIEUNHAPs">
    <Type Name="PHIEUNHAP">
      <Column Name="MAPN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIENNHAP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PHIEUNHAP_CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs" ThisKey="MAPN" OtherKey="MAPN" Type="CHITIETPHIEUNHAP" />
      <Association Name="NHACC_PHIEUNHAP" Member="NHACC" ThisKey="MANCC" OtherKey="MANCC" Type="NHACC" IsForeignKey="true" />
      <Association Name="NHANVIEN_PHIEUNHAP" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETPHIEUNHAP" Member="CHITIETPHIEUNHAPs">
    <Type Name="CHITIETPHIEUNHAP">
      <Column Name="MACTPN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONGSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIATIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PHIEUNHAP_CHITIETPHIEUNHAP" Member="PHIEUNHAP" ThisKey="MAPN" OtherKey="MAPN" Type="PHIEUNHAP" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETPHIEUNHAP" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMSUCO" Member="DMSUCOs">
    <Type Name="DMSUCO">
      <Column Name="MASC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSUCO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DMSUCO_CTBBSC" Member="CTBBSCs" ThisKey="MASC" OtherKey="MASC" Type="CTBBSC" />
    </Type>
  </Table>
  <Table Name="dbo.CTPHIEUDATHANGNCC" Member="CTPHIEUDATHANGNCCs">
    <Type Name="CTPHIEUDATHANGNCC">
      <Column Name="SODONHANG" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="PHIEUDATHANGNCC_CTPHIEUDATHANGNCC" Member="PHIEUDATHANGNCC" ThisKey="SODONHANG" OtherKey="SODONHANG" Type="PHIEUDATHANGNCC" IsForeignKey="true" />
      <Association Name="SANPHAM_CTPHIEUDATHANGNCC" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.SINHMA_HDB" Method="SINHMA_HDB" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.SINHMA_KH" Method="SINHMA_KH" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.DSGIAY_NHACC" Method="DSGIAY_NHACC" IsComposable="true">
    <Parameter Name="NCC" Parameter="nCC" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="DSGIAY_NHACCResult">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAU" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CHATLIEU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_PBH" Method="XEMTT_PBH" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_PBHResult">
      <Column Name="MABH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYHETHANDOITRA" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SINHMA_PBH" Method="SINHMA_PBH" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.SINHMA_TK" Method="SINHMA_TK" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.tongdoanhso" Method="tongdoanhso" IsComposable="true">
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.tongdoanhthu" Method="tongdoanhthu" IsComposable="true">
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.tiencttkds" Method="tiencttkds" IsComposable="true">
    <Parameter Name="MSP" Parameter="mSP" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.TONGSOSC" Method="TONGSOSC" IsComposable="true">
    <Parameter Name="MSC" Parameter="mSC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.TONGSOSC_frmtksc" Method="TONGSOSC_frmtksc" IsComposable="true">
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.tongthuchisc" Method="tongthuchisc" IsComposable="true">
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.tongthuchicttksc" Method="tongthuchicttksc" IsComposable="true">
    <Parameter Name="MSC" Parameter="mSC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.rongthucuoinam" Method="rongthucuoinam" IsComposable="true">
    <Parameter Name="NBD" Parameter="nBD" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NKT" Parameter="nKT" Type="System.DateTime" DbType="Date" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.SINHMA_NV" Method="SINHMA_NV" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.XEMTT_BBSC" Method="XEMTT_BBSC" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_BBSCResult">
      <Column Name="MABB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYLAPBB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_CTBBSC" Method="XEMTT_CTBBSC" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_CTBBSCResult">
      <Column Name="MABB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MASC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="THU_CHI" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_CTHoaDonBan" Method="XEMTT_CTHoaDonBan" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_CTHoaDonBanResult">
      <Column Name="MACTHDB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MABH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAKM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONGBAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIABAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOSIZE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_HoaDonBan" Method="XEMTT_HoaDonBan" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_HoaDonBanResult">
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MAKHTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KHVANGLAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CHIECKHAU" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SINHMA_CTHDB" Method="SINHMA_CTHDB" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.XEMTT_KHUYENMAI" Method="XEMTT_KHUYENMAI" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_KHUYENMAIResult">
      <Column Name="MAKM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOIDUNG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PHANTRAM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="APDUNG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_CTKHUYENMAI" Method="XEMTT_CTKHUYENMAI" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_CTKHUYENMAIResult">
      <Column Name="MAKM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NBD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_DDHKH" Method="XEMTT_DDHKH" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_DDHKHResult">
      <Column Name="MADH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TONGSLSANPHAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_GIAOHANG" Method="XEMTT_GIAOHANG" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_GIAOHANGResult">
      <Column Name="MADH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MANVGIAOHANG" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYGIOGIAOHANG" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_CTDDHKH" Method="XEMTT_CTDDHKH" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_CTDDHKHResult">
      <Column Name="MADH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONGSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIATIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_SIZE" Method="XEMTT_SIZE" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_SIZEResult">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SOSIZE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONGTON" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_kHO" Method="XEMTT_kHO" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_kHOResult">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MADMSP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_SANPHAM" Method="XEMTT_SANPHAM" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_SANPHAMResult">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MADMSP" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MAU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CHATLIEU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SOLUONGSIZE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TINHTRANGSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_CTKHUYENMAI" Method="XEMTT_CTKHUYENMAI1" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_CTKHUYENMAIResult1">
      <Column Name="MAKM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NBD" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NKT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_TTNCC" Method="XEMTT_TTNCC" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_TTNCCResult">
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTNHACC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHINCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_PHIEUNHAP" Method="XEMTT_PHIEUNHAP" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_PHIEUNHAPResult">
      <Column Name="MAPN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TONGTIENNHAP" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_CTPHIEUNHAP" Method="XEMTT_CTPHIEUNHAP" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_CTPHIEUNHAPResult">
      <Column Name="MACTPN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MAPN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONGSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIATIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SINHMA_BBSC" Method="SINHMA_BBSC" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.SINHMA_DMSP" Method="SINHMA_DMSP" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.SINHMA_Khachhang" Method="SINHMA_Khachhang" IsComposable="true">
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.XEMTT_TTKHACHHANG" Method="XEMTT_TTKHACHHANG" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_TTKHACHHANGResult">
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TENKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDTKHACHHANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIACHIKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_TTNHANVIEN" Method="XEMTT_TTNHANVIEN" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_TTNHANVIENResult">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SOCMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIENTHOAINV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MACHUCVU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TINHTRANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYVAOLAM" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MANQL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="THUONGDOANHTHU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LUONGTRU" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="THUCLANH" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_TTTAIKHOANNV" Method="XEMTT_TTTAIKHOANNV" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_TTTAIKHOANNVResult">
      <Column Name="TENDN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MK" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEMTT_TTCHUCVU" Method="XEMTT_TTCHUCVU" IsComposable="true">
    <Parameter Name="TLG" Parameter="tLG" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="XEMTT_TTCHUCVUResult">
      <Column Name="MACHUCVU" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TENCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LUONG" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.XEM_NHOMND" Method="XEM_NHOMND" IsComposable="true">
    <Parameter Name="TENKH" Parameter="tENKH" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="XEM_NHOMNDResult">
      <Column Name="MANHOM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TENNHOMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>